# Generated by Django 4.2 on 2024-10-01 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manuscript',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
